import { StyleSheet, StatusBar } from "react-native";
import { shadowOffset } from "react-native/Libraries/Components/View/ReactNativeStyleAttributes";

export const globalStyles = StyleSheet.create({
    global: {
        marginTop: StatusBar.currentHeight,
        height: '100%',
    },
    container_enter_screens: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#a77ce8",
    },
    textInput: {
        borderColor: "black",
        color: "#000000",
        width: '90%',
        padding: 5,
        paddingRight: 10,
        fontSize: 17,
        borderWidth: 2,
        marginBottom: 4,
        textAlign: "right",
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        backgroundColor: "#fffffa",
    },
    loading: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "#a77ce8",
    },
    ////////////////////////////////////////////////
    landing_imageArea: {
        margin: 25,
    },
    landing_title_text: {
        color: "#fdc123",
        fontSize: 50,
        fontWeight: "bold",
        margin: -5,
    },
    landing_reg_button: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 180,
        marginTop: 2,
        marginBottom: 15,
        paddingVertical: 10,
        paddingHorizontal: 3,
        borderRadius: 7,
        elevation: 2,
        backgroundColor: "#000000",
    },
    landing_reg_btn_text: {
        color: "#fdc123",
        fontSize: 15,
        fontWeight: "bold",
    },
    landing_log_button: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 180,
        marginTop: 15,
        marginBottom: 10,
        paddingVertical: 10,
        paddingHorizontal: 3,
        borderRadius: 7,
        elevation: 2,
        backgroundColor: "#fdc123",
    },
    landing_log_btn_text: {
        color: "#000000",
        fontSize: 15,
        fontWeight: "bold",
    },
    ////////////////////////////////////////////////
    enter_button: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 15,
        marginBottom: 15,
        paddingVertical: 10,
        paddingHorizontal: 35,
        borderRadius: 10,
        elevation: 3,
        backgroundColor: "#fdc123",
    },
    enter_btn_text: {
        color: "#000000",
        fontSize: 20,
        fontWeight: "bold",
    },
    logo: {
        width: 100,
        height: 100,
        bottom: 20,
        borderRadius: 100,
        overflow: "hidden",
    },
    logo_image_area: {
        flex: 1,
        height: undefined,
        width: undefined,
    },
    already_have: {
        fontSize: 15,
        fontFamily: "sans-serif",
        color: "black",
        fontWeight: "bold",
        paddingTop: 20,
    },
    blue_btn: {
        paddingTop: 20,
        marginBottom: 4,
        fontSize: 15,
        fontFamily: "sans-serif",
        color: "blue",
        fontWeight: "bold",
        textDecorationLine: 'underline'
    },
    forgot_title: {
        top: 1,
        marginBottom: 30,
        fontSize: 25,
        fontWeight: "bold",
        fontFamily: "sans-serif",
    },
    ////////////////////////////////////////////////
    fill_title_text: {
        color: "#fdc123",
        fontSize: 30,
        fontWeight: "bold",
    },
    datePicker: {
        flexDirection: "row",
        alignContent: "center",
        width: 315,
    },
    picker: {
        flex: 1,
        margin: 2,
        fontSize: 10,
    },
    ////////////////////////////////////////////////
    drawer_pic: {
        height: 85,
        width: 85,
        borderRadius: 100,
        margin: '3%',
    },
    drawer_name: {
        color: "#fff",
        fontSize: 20,
        margin: '1%',
    },
    drawer_props: {
        flex: 1,
        backgroundColor: "#fff",
        paddingTop: '2%',
    },
    sign_out_area: {
        padding: '5%',
        borderTopWidth: 1,
        borderTopColor: "#ccc",
    },
    sign_out: {
        flexDirection: "row",
        alignItems: "center",
    },
    sign_out_text: {
        fontSize: 15,
        marginRight: '3%',
    },
    stage1: {
        flexDirection: "row",
        alignContent: "space-between",
        alignItems: "center",
        justifyContent: "center",
        marginTop: '2%',
        marginBottom: '5%',
    },
    stage2: {
        alignItems: "center",
        justifyContent: "center",
        marginBottom: '5%',
    },
    stage3: {
        alignItems: "center",
        justifyContent: "center",
        marginBottom: '5%',
    },
    touchable_profile_pic: {
        height: 50,
        width: 50,
        borderRadius: 100,
        margin: '1%',
    },
    profile_edit_btn: {
        position: 'absolute',
        left: '2%',
        top: '2%',
        backgroundColor: "#a77ce8",
        borderWidth: 2,
        borderRadius: 100,
        padding: 5,
    },
    profile_edit_btn_text: {
        color: "#fdc123",
        fontSize: 15,
        fontWeight: "bold",
    },
    profile_pic: {
        width: 100,
        height: 100,
        borderRadius: 50,
        overflow: "hidden",
        //alignItems: "center",
        justifyContent: "center",
        marginBottom: '2%',
    },
    profile_title: {
        fontWeight: "bold",
        fontSize: 25,
    },
    edit_profile_pic: {
        width: 150,
        height: 150,
        borderRadius: 75,
        overflow: "hidden",
        //alignItems: "center",
        justifyContent: "center",
        marginBottom: '3%',
    },
    profile_details: {
        fontWeight: "bold",
        fontSize: 13,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 10,
    },
    picAndDetails: {
        alignItems: "center",
        justifyContent: "center",
        // marginRight: 20,
        width: '70%',
    },
    side_details: {
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        //marginLeft: 20,
        width: '30%',
    },
    circle_details: {
        width: '78%',
        height: 82,
        backgroundColor: "#fdc123",
        borderColor: "black",
        borderWidth: 1,
        borderRadius: 100,
        justifyContent: "center",
        margin: 5,
    },
    circle_details_text: {
        fontWeight: "bold",
        textAlign: "center",
        justifyContent: "center",
        fontSize: 12,
        flexWrap: "wrap",
    },
    line: {
        width: '100%',
        borderWidth: 1,
        borderColor: 'black',
        marginBottom: '5%',
    },
    ////////////////////////////////////////////////
    plus_btn: {
        position: 'absolute',
        bottom: '7%',
        left: '5%',
        borderColor: 'black',
        borderStyle: 'solid',
        backgroundColor: "#a77ce8",
        textAlign: "center",
        borderWidth: 2,
        borderRadius: 100,
        padding: 5,
    },
    plus_btn_text: {
        color: "#fdc123",
        fontSize: 20,
        fontWeight: "bold",
        paddingLeft: 10,
        paddingRight: 10,
    },
    title_creat_post: {
        textAlign: "center",
        fontSize: 25,
        color: "#fdc123",
        fontWeight: "bold",
        top: '2%',
        marginBottom: '10%',
    },
    create_post_text: {
        marginLeft: '4%',
        borderColor: "black",
        color: "#000000",
        width: '92%',
        height: '40%',
        textAlignVertical: 'top',
        marginBottom: '3%',
        padding: 10,
        fontSize: 20,
        borderWidth: 1,
        textAlign: "right",
        borderRadius: 10,
    },
    choose_img: {
        width: '15%',
        left: '80%',
        borderColor: 'black',
        borderStyle: 'solid',
        backgroundColor: "#fdc123",
        textAlign: "center",
        borderWidth: 2,
        borderRadius: 8,
    },
    choose_img_text: {
        fontSize: 25,
        fontWeight: "bold",
        textAlign: "center"
    },
    create_post_img: {
        height: '75%',
        marginTop: '2%',
        //width: '92%',
        //marginLeft: '4%',
        resizeMode: 'stretch',
    },
    to_post: {
        position: 'absolute',
        bottom: '8%',
        left: '5%',
        borderColor: 'black',
        borderStyle: 'solid',
        backgroundColor: "#a77ce8",
        textAlign: "center",
        borderWidth: 2,
        borderRadius: 100,
        padding: 10,
    },
    to_post_text: {
        color: "#fdc123",
        fontWeight: "bold",
        fontSize: 20,
    },
    ////////////////////////////////////////////////
    feed: {
        bottom: '4%',
        backgroundColor: "#d3d3d3",
    },
    empty_feed: {
        color: "#fdc123",
        textAlign: "center",
        fontSize: 30,
        fontWeight: "bold",
        alignItems: "center",
    },
    list_of_posts: {
        width: '100%',
        marginBottom: '2%',
        backgroundColor: "#ffffff"
    },
    post: {
        width: '100%',
        marginBottom: '-4%',
        paddingBottom: '1%',
        backgroundColor: "#ffffff"
    },
    post_text: {
        textAlign: "right",
        margin: '3%',
        fontSize: 17,
    },
    post_img: {
        width: '100%',
        height: 375,
        paddingBottom: '2%',
        resizeMode : 'stretch',
        resizeMode : 'contain',
    },
    user_pic: {
        width: 40,
        height: 40,
        borderRadius: 100,
        overflow: "hidden",
        margin: '2%',
    },
    user_name: {
        fontWeight: "bold",
    },
    user_pic_name: {
        flexDirection: "row",
        alignItems: "center",

    },
    take_a_pic: {
        flexDirection: "row",
        marginBottom: '7%',
    },
    take_a_pic_btn: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: "row",
        padding: 10,
        margin: 10,
        borderRadius: 20,
        backgroundColor: "#000000",
    },
    take_a_pic_btn_text: {
        fontSize: 15,
        color: "#fdc123",
        fontWeight: "bold",
    },
    like_comment: {
        flexDirection: "row",
        justifyContent: "center",
        margin: '2%',
        paddingBottom: '2%',
    },
    like_comment_btn: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: "row",
        
    },
    like_comment_btn_txt: {
        color: "#000000",
        fontWeight: "bold",
        fontSize: 18,
        marginRight: '8%',
    },
    /////////////////Forum_Topic/////////////////
    forum_title_text: {
        color: "#fdc123",
        fontSize: 40,
        fontWeight: "bold",
        textAlign: "center",
        marginBottom: '2%',
    },
    forums_titles: {
        margin: '2%',
        alignItems: "center",
        shadowColor: "black",
        shadowOpacity: 0.8,
        shadowOffset: {width: 1, height: 13},
        shadowRadius: 20,
    },
    forums_titles_txt: {
        fontSize: 35,
        fontWeight: "bold",
        color: "#a77ce8",
    },
    /////////////////Forum_Subject/////////////////
    open_sub_btn: {
        position: 'absolute',
        top: '2%',
        right: '3%',
        borderColor: 'black',
        borderStyle: 'solid',
        backgroundColor: "#a77ce8",
        textAlign: "center",
        borderWidth: 2,
        borderRadius: 100,
        padding: 5,
    },
    open_sub_btn_text: {
        color: "#fdc123",
        fontSize: 15,
        fontWeight: "bold",
        paddingLeft: 10,
        paddingRight: 10,
    },
    subjects: {
        marginBottom: '3%',
    },
    subjects_txt: {
        fontSize: 15,
        margin: '2%',
        marginBottom: '5%',
    },
    /////////////////Forum_Create_Thread/////////////////

    /////////////////Forum_Thread/////////////////

    /////////////////Forum_Comment/////////////////

});